

# function _foo()
#  {
#      echo -e "\n"
 
#      declare -p COMP_WORDS
#      declare -p COMP_CWORD
#      declare -p COMP_LINE
#      declare -p COMP_WORDBREAKS
#  }
# complete -F _foo foo



#input COMP_WORDS array
#output COMPREPLY
hand__completion_entry() {
	local cmd comp
	for ((i=1; i<${COMP_CWORD}; i++ )); do
		if [ "${COMP_WORDS[i]:0:2}" == "--" ]; then
			continue
		fi
		cmd="${cmd}_${COMP_WORDS[i]}"
	done

	if [ "$(declare -F hand${cmd}__completion)" ]; then
		comp=$(hand${cmd}__completion ${COMP_WORDS[@]:i+1})
	else
		comp=`eval echo '$'hand__complist${cmd}`
	fi

	if [ -z "$comp" ]; then
		COMPREPLY=($(compgen -fd -- "${COMP_WORDS[COMP_CWORD]}"))
		return
	fi

	#echo math=${COMP_WORDS[i]}
	COMPREPLY=($(compgen -W "$comp" -- "${COMP_WORDS[COMP_CWORD]}"))
	return
}

if [[ `hand__shell_name` = "zsh" ]]; then
	fpath=($hand__path/completions $fpath)
	autoload -U _hand
	compdef _hand hand h hs hh hand__hub
else
	complete -F hand__completion_entry h
	complete -F hand__completion_entry hand
	complete -F hand__completion_entry hs
	complete -F hand__completion_entry hh
fi


#gen $path $cmd
hand__completions_generate()
{
	# echo pathx=$pathx
	# echo ">>" Generate "$@ ============="
	local pathx=$1
	# local path1
	# local path2
	local cmd=$2
	# local item
	local list=
	local list2=
	local list3=
	local list4=

	if [ -d $hand__path/hand/$pathx ]; then
		list=`ls $hand__path/hand/$pathx | grep ".cmd"`
		list2=`ls -F $hand__path/hand/$pathx | grep "/$" | sed '/^_/d' | sed 's/\/$//g' `
	fi

	if [ -d $hand__config_path/hand/$pathx ]; then
		list3=`ls $hand__config_path/hand/$pathx | grep ".cmd"`
		list4=`ls -F $hand__config_path/hand/$pathx | grep "/$" | sed '/^_/d' | sed 's/\/$//g'  `
	fi

	if [ -z "$list" ] && [ -z "$list2" ] && [ -z "$list3" ] && [ -z "$list4" ]; then
		# echo "$pathx is not a path!!!"
		return 1
	fi

	hand echo white "completion: hand$cmd"
	
	list=(`echo $list $list2 $list3 $list4`)
	# echo list=${list[@]}

	local words=`echo ${list[@]} | sed 's/\.cmd//g' | sed 's/\.sh//g'   `
	# echo words=$words

	echo hand__complist${cmd}="'${words}'" >> $hand__config_path/.completions.sh

	# echo "-------------1"
	local item=
	for item in ${list[@]}
	do
		# echo "for item=$item:"
		if [ "${item#*.cmd*}" ]; then
			# echo item=$item
			# echo cmd=$cmd
			hand__completions_generate $pathx/$item "${cmd}_${item}"
		fi
		# echo "***2"
	done
}

hand__completions_load_sub()
{
	local f
	#echo "load sub..."
	for f in $(find -L $hand__path/hand $hand__config_path/hand -name "*.comp.sh")
	do
		hand echo white "load $f"
		#echo "" >> $hand__config_path/.completions.sh
		#echo "# $f" >> $hand__config_path/.completions.sh
		echo -e "\n" >> $hand__config_path/.completions.sh
		cat $f >> $hand__config_path/.completions.sh
	done
}

#generate completions by hand dir
if [ ! -f $hand__config_path/.completions.sh ]; then
	
	echo -e "#\n# THIS FILE IS GENERATED BY PROGRAM\n# DO NOT EDIT HERE!\n#\n" >> $hand__config_path/.completions.sh

	echo -e "#\n# Generate by files tree\n#" >> $hand__config_path/.completions.sh
	hand echo yellow "generating completions..."
	hand__completions_generate

	echo -e "\n\n#\n# Generate by .comp.sh file\n#" >> $hand__config_path/.completions.sh
	hand echo yellow "load sub completions..."
	hand__completions_load_sub
fi

source $hand__config_path/.completions.sh
