#!/bin/bash

# function _foo()
#  {
#      echo -e "\n"
 
#      declare -p COMP_WORDS
#      declare -p COMP_CWORD
#      declare -p COMP_LINE
#      declare -p COMP_WORDBREAKS
#  }
# complete -F _foo foo



#input COMP_WORDS array
#output COMPREPLY
hand__completion_entry() {
	local cmd comp
	for(( i=1;i<${COMP_CWORD};i++)) do
		cmd="${cmd}_${COMP_WORDS[i]}"
	done

	if [ "$(declare -F hand${cmd}__completion)" ]; then
		comp=$(hand${cmd}__completion ${COMP_WORDS[@]:i+1})
	else
		comp=`eval echo '$'hand${cmd}__completion_list`
	fi

	if [ -z "$comp" ]; then
		COMPREPLY=($(compgen -fd -- "${COMP_WORDS[COMP_CWORD]}"))
		return
	fi

	#echo math=${COMP_WORDS[i]}
	COMPREPLY=($(compgen -W "$comp" -- "${COMP_WORDS[COMP_CWORD]}"))
	return
}
complete -F hand__completion_entry h
complete -F hand__completion_entry hand



#gen $path $cmd
hand__completions_generate()
{

	local path=$1
	local path1
	local path2
	local cmd=$2
	local item
	local list

	if [ -d $HAND_PATH/hand/$path ]; then
		list=" $(ls $HAND_PATH/hand/$path | sed '/\.comp\.sh$/d')"
	fi

	if [ -d $hand__config_path/hand/$path ]; then
		list+=" $(ls $hand__config_path/hand/$path | sed '/\.comp\.sh$/d')"
	fi

	if [ -z "$list" ]; then
		echo "$path is not a path!!!"
		return 1
	fi

	hand echo debug "completion: hand$cmd"
	#echo list=$list
	#local list="$(ls $path | sed 's/.sh$//')"
	#eval hand${cmd}__completion_list='"$list"'

	#echo ===
	#echo path1=$path1
	#echo path2=$path2
	#ls $path1;ls $path2
	#echo ===

	local words="$(echo $list | sed 's/\.sh//g')"
	#eval hand${cmd}__completion_list='"${words}"'
	
	#eval hand${cmd}__completion_list='"$(echo "$list" | sed 's/\.sh//')"'

	#eval echo list2='$'hand${cmd}__completion_list
	eval echo hand${cmd}__completion_list='\"'${words}'\"' >> $hand__completion_prebuild


	for item in ${list}
	do
		if [ "${item##*.sh}" ]; then
			#echo $item
			hand__completions_generate $path/$item "_$item"
		fi
	done
}

hand__completions_load_sub()
{
	local f
	#echo "load sub..."
	for f in $(find $HAND_PATH/hand $hand__config_path/hand -name "*.comp.sh")
	do
		hand echo debug "source $f"
		#echo "" >> $hand__completion_prebuild
		#echo "# $f" >> $hand__completion_prebuild
		echo -e "\n" >> $hand__completion_prebuild
		cat $f >> $hand__completion_prebuild
	done
}

#generate completions by hand dir
if [ ! -f $hand__completion_prebuild ]; then
	
	echo -e "#\n# THIS FILE IS GENERATED BY PROGRAM\n# DO NOT EDIT HERE!\n\n" >> $hand__completion_prebuild

	hand echo debug "generating completions..."
	hand__completions_generate

	hand echo debug "load sub completions..."
	hand__completions_load_sub
fi

source $hand__completion_prebuild