#!/bin/bash

HAND_PATH="example_path"
source $HAND_PATH/hand.sh

#do empty
if [ $# -eq 0 ]; then
	hand
	exit 0
fi

#options
if [ "$1" == "--work" ]; then
	hand work $2
	shift
	shift
fi


#start do alias cmd
cmd=`alias $1`
if [ $? -eq 0 ]; then
	echo "got alias!"
	cmd=${cmd#*=}
	cmd=${cmd//\'/}
	#echo cmd=$cmd
	if [ "$cmd" != "" ]; then
		shift
		echo $cmd $*
		$cmd $*
		exit $?
	fi
fi

#start do normal hand cmd
echo "got normal!"
echo hand $*
hand $*

