
#input COMP_WORDS array
#output COMPREPLY
hand__completion_entry() {
	local cmd comp
	for ((i=1; i<${COMP_CWORD}; i++ )); do
		if [ "${COMP_WORDS[i]:0:2}" == "--" ]; then
			continue
		fi
		cmd="${cmd}_${COMP_WORDS[i]}"
	done

	if [ "$(declare -F hand${cmd}__completion)" ]; then
		comp=$(hand${cmd}__completion ${COMP_WORDS[@]:i+1})
	else
		comp=`eval echo '$'hand__complist${cmd}`
	fi

	if [ -z "$comp" ]; then
		COMPREPLY=($(compgen -fd -- "${COMP_WORDS[COMP_CWORD]}"))
		return
	fi

	#echo math=${COMP_WORDS[i]}
	COMPREPLY=($(compgen -W "$comp" -- "${COMP_WORDS[COMP_CWORD]}"))
	return
}

if [[ `hand__shell_name` = "zsh" ]]; then
	fpath=($hand__path/completions $fpath)
	autoload -U _hand
	compdef _hand hand h hs hh hand__hub
else
	complete -F hand__completion_entry h
	complete -F hand__completion_entry hand
	complete -F hand__completion_entry hs
	complete -F hand__completion_entry hh
fi

#gen $path $cmd
hand__completions_generate()
{
	# echo ">>" Generate "$@ ============="
	local pathx=$1
	local cmd=$2

	local dirs=
	local cmdshfiles=
	local search_path=
	for search_path in $hand__path/hand/$pathx $hand__config_path/hand/$pathx
	do
		if [ -d $search_path ]; then
			cmdshfiles=`find -L $search_path -maxdepth 2  -type f -name cmd.sh | head -n 1`
			if [ "$cmdshfiles" != "" ]; then
				# echo ">>>cmdshfile=$cmdshfiles, not empty!<<<"
				dirs="${dirs} "`ls -F $search_path | grep "/$" | sed 's/\/$//g' `
			fi
		fi
	done

	# echo dirs=$dirs
	if [ "$dirs" = " " ] || [ "$dirs" = "" ]; then
		return
	fi

	hand echo white "completion: hand$cmd"
	local list=(`echo $dirs`)
	# echo list=${list[@]}

	local words=`echo ${list[@]} `
	# echo words=$words

	echo hand__complist${cmd}="'${words}'" >> $hand__config_path/.completions.sh

	# echo "-------------1"
	local item=
	for item in ${list[@]}
	do
		hand__completions_generate $pathx/$item "${cmd}_${item}"
	done
}

hand__completions_load_sub()
{
	local f
	#echo "load sub..."
	for f in $(find -L $hand__path/hand $hand__config_path/hand -name "comp.sh")
	do
		hand echo white "load $f"
		#echo "" >> $hand__config_path/.completions.sh
		#echo "# $f" >> $hand__config_path/.completions.sh
		echo -e "\n" >> $hand__config_path/.completions.sh
		cat $f >> $hand__config_path/.completions.sh
	done
}

#generate completions by hand dir
if [ ! -f $hand__config_path/.completions.sh ]; then
	
	echo -e "#\n# THIS FILE IS GENERATED BY PROGRAM\n# DO NOT EDIT HERE!\n#\n" >> $hand__config_path/.completions.sh

	echo -e "#\n# Generate by files tree\n#" >> $hand__config_path/.completions.sh
	hand echo yellow "generating completions..."
	hand__completions_generate

	echo -e "\n\n#\n# Generate by comp.sh file\n#" >> $hand__config_path/.completions.sh
	hand echo yellow "load sub completions..."
	hand__completions_load_sub
fi

# load
source $hand__config_path/.completions.sh
